### ISSUE TITLE
jinora

### ISSUE THREAD

**Issue by Slind14** [simonv3/public-slack-channels#2]
Hey,
are you aware of https://github.com/sdslabs/jinora ?

**Comment by simonv3** [comment]
@Slind14 I wasn't at all! This isn't really the intent of this repository, but that could be interesting.

**Comment by Slind14** [comment]
alright, no description on the repo, so I have literally no idea on what exactly it does, aims to.. :)
Mind sharing what you aim for with this project?

**Comment by simonv3** [comment]
Just a list of slack channels that are publicly available and that anyone can join. Kind of like IRC rooms, I hadn't seen a resource like that out there. (open source channels, interest channels, etc)

http://simonv3.github.io/public-slack-channels/

Sorry I don't have a Readme yet, I pretty quickly threw this up as a jekyll blog. You can add public channels that you know of under Slack in [_posts](https://github.com/simonv3/public-slack-channels/tree/gh-pages/_posts)

Original musings on this are here:

http://www.piranhabay.co.uk/the-slackification-of-interest-groups/
